# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host:8080, host_ip: '127.0.0.1'
  
  config.vm.provider "virtualbox" do |vb| 
	vb.name = "Webclient"
	config.vm.hostname = "webclient"
	
	end
end
